# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  inviscan-api-project: 'Inviscan.API/Inviscan.API.csproj'
  inviscan-api-tests-project: 'Inviscan.API.Tests/Inviscan.API.Tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '$(inviscan-api-project)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: '$(inviscan-api-tests-project)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(inviscan-api-project)\bin\Release'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pakki(428e06a1-9138-47fe-9d07-7070c6831afc)'
    appType: 'webApp'
    WebAppName: 'Inviscan-API'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'